<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

/**
 * Safely switches which central server THIS device's app talks to,
 * without ever touching .env's CENTRAL_API_URL -- see config/elikas.php's
 * own docblock for the exact incident this exists to prevent (a local
 * test entry syncing straight into the live production database because
 * there was previously no dev-safe way to point this app at a local
 * server, and no visible indicator when accidentally pointed at
 * production during testing).
 *
 * Writes to MULTIPLE physical locations, not just storage_path() --
 * confirmed real incident: running this command via a bare CLI
 * invocation (php artisan, outside the actual NativePHP/Electron
 * runtime) only ever touched THIS PROJECT's own storage/app/ directory.
 * The real running app (native:serve, or a packaged build) never reads
 * from there at all -- NativePHP's NativeServiceProvider::
 * rewriteStoragePath() redirects storage_path() to Electron's own
 * userData directory (app.getPath('userData') + '/storage', a pure
 * Electron JS API with no PHP-callable equivalent) for EVERY real run,
 * dev or packaged, whenever app.debug is false (this app's .env always
 * sets APP_DEBUG=false, even in dev). A bare CLI command never has that
 * redirection applied, so it was silently writing to a file nothing
 * ever reads.
 *
 * True runtime-accurate resolution (asking Electron itself) isn't
 * achievable from bare CLI -- app.getPath('userData') only exists
 * inside a live Electron process, injected into the spawned PHP
 * process's OWN environment (NATIVEPHP_STORAGE_PATH), never written to
 * any file a separate process could read. Confirmed via
 * vendor/nativephp/electron/resources/js/electron-plugin/src/server/php.ts:
 * `storagePath = join(app.getPath('userData'), 'storage')`.
 *
 * Instead, this deterministically RECOMPUTES that same path from a
 * real on-disk artifact: vendor/nativephp/electron/resources/js/
 * package.json's own "name" field -- confirmed to be exactly what
 * Electron's app.getPath('userData') keys off on Windows/macOS/Linux,
 * and confirmed to already read "e-likas-dev" (matching the real
 * AppData\Roaming\e-likas-dev\ folder found on this device) for
 * native:serve, vs "e-likas" for a packaged native:build. That file is
 * itself regenerated by NativePHP on every native:serve/native:build
 * run, so this always recomputes against whichever one actually ran
 * last -- not a hardcoded folder name guess.
 */
class ApiTargetCommand extends Command
{
    protected $signature = 'elikas:api-target {target? : "local", "production", or a full URL. Omit to just show the current target.}';

    protected $description = 'Show or switch which central server this device talks to (local dev vs production) -- never edits .env';

    /**
     * Every real physical location that might need updating -- the
     * project's own storage/app/ (what a bare CLI/test run reads) plus,
     * when resolvable, the real NativePHP/Electron userData storage
     * directory (what an actual running native:serve or packaged app
     * reads). Always includes at least the project path.
     *
     * @return list<string>
     */
    private function overrideFiles(): array
    {
        $paths = [storage_path('app/dev-api-target.txt')];

        if ($userDataStoragePath = $this->resolveNativePhpUserDataStoragePath()) {
            $paths[] = $userDataStoragePath.'/app/dev-api-target.txt';
        }

        return array_unique($paths);
    }

    private function resolveNativePhpUserDataStoragePath(): ?string
    {
        $packageJsonPath = base_path('vendor/nativephp/electron/resources/js/package.json');
        if (! is_file($packageJsonPath)) {
            return null;
        }

        $appName = json_decode(file_get_contents($packageJsonPath), true)['name'] ?? null;
        if (! is_string($appName) || $appName === '') {
            return null;
        }

        // Matches Electron's own app.getPath('userData') convention
        // exactly -- see this class's own docblock for the confirmed
        // source (server/php.ts) this mirrors.
        $userDataDir = match (PHP_OS_FAMILY) {
            'Windows' => getenv('APPDATA') ? rtrim(getenv('APPDATA'), '/\\')."/{$appName}" : null,
            'Darwin' => getenv('HOME') ? rtrim(getenv('HOME'), '/')."/Library/Application Support/{$appName}" : null,
            default => getenv('HOME') ? rtrim(getenv('HOME'), '/')."/.config/{$appName}" : null,
        };

        return $userDataDir ? "{$userDataDir}/storage" : null;
    }

    public function handle(): int
    {
        $target = $this->argument('target');
        $files = $this->overrideFiles();

        if (! $target) {
            $this->showCurrent($files);

            return self::SUCCESS;
        }

        if ($target === 'production') {
            foreach ($files as $file) {
                if (file_exists($file)) {
                    unlink($file);
                }
            }
            $this->info('Override cleared on '.count($files).' location(s) -- back to production ('.config('elikas.production_api_url').').');
            $this->listFiles($files);

            return self::SUCCESS;
        }

        $url = $target === 'local' ? 'http://127.0.0.1:8000/api/v1' : $target;

        if (! filter_var($url, FILTER_VALIDATE_URL)) {
            $this->error("\"{$target}\" isn't \"local\", \"production\", or a valid URL.");

            return self::FAILURE;
        }

        foreach ($files as $file) {
            if (! is_dir(dirname($file))) {
                mkdir(dirname($file), 0755, true);
            }
            file_put_contents($file, $url);
        }

        $this->warn("Now targeting {$url} on ".count($files)." location(s) -- this device's app will show a warning banner on every page until you run `php artisan elikas:api-target production`.");
        $this->listFiles($files);

        return self::SUCCESS;
    }

    private function listFiles(array $files): void
    {
        foreach ($files as $file) {
            $this->line("  - {$file}");
        }
    }

    private function showCurrent(array $files): void
    {
        // config('elikas.central_api_url') alone would only ever reflect
        // the FIRST of these (storage_path() resolves to exactly one
        // location per process) -- reporting on every real file
        // individually is the whole point here, so this can never again
        // look "cleared" from one vantage point while a real running app
        // still reads an untouched override elsewhere.
        $this->line('Production URL: '.config('elikas.production_api_url'));
        $this->newLine();

        foreach ($files as $file) {
            if (! file_exists($file)) {
                $this->line("[production, no override] {$file}");

                continue;
            }

            $this->line('[OVERRIDE ACTIVE: '.trim(file_get_contents($file))."] {$file}");
        }
    }
}
